In [1]:
import numpy as np

In [2]:
m_bullets = np.array([0.514, 0.512, 0.512, 0.504, 0.512])
dx = np.array([10.50, 11.50, 11.00, 10.75, 11.25])
dx = 0.001 * dx
L = 2.212
M = np.array([2905] * 5)
g = 9.8

In [3]:
def speed(m, M, dx, g, L):
    return (np.sqrt(g/L)*M*dx)/ m

In [4]:
u = speed(m_bullets, M, dx, g, L)

In [5]:
u = speed(m_bullets, M, dx, g, L)
u = np.round(u, 2)
u

array([124.91, 137.34, 131.37, 130.42, 134.35])

In [6]:
print(np.mean(u))

131.678


In [7]:
def sigma(u):
    return np.sqrt(0.2*np.sum(np.power(u-np.mean(u),2)))

In [8]:
print(np.round(sigma(u), 2))

4.16


In [9]:
e_u = np.round(4 / 132, 2)
e_u

0.03

$$ u = 132 \pm 4 \textrm{ м/c}$$

In [10]:
print(np.mean(dx))

0.011000000000000001


In [11]:
print(np.sqrt(np.power(0.5, 2) + np.power(0.25, 2)))

0.5590169943749475


In [12]:
e_dx =np.round(0.56 / 11, 3)
e_dx

0.051

$$ dx = 11.00 \pm 0.56 \textrm{ мм}$$

In [13]:
e_m = np.mean(0.005 / m_bullets)
e_m

0.009789027275955778

$$ \sigma_{m} = 0.005 \textrm{ г}$$

$$ L = 221.2 \pm 0.05 \textrm{ см}$$

In [14]:
e_L = 0.05 / 221.2
e_L

0.00022603978300180834

In [15]:
e_M = 5 / 2905
e_M

0.0017211703958691911

In [19]:
sigma_sqrt_L = 0.05*1/(2*np.sqrt(221.2))
sigma_sqrt_L

0.0016809215590034546

In [20]:
e_sqrt_L = sigma_sqrt_L / np.sqrt(221.2)
e_sqrt_L

0.00011301989150090417

In [21]:
epsilon_total = np.sqrt(np.power(e_m,2) + np.power(e_M,2) + np.power(e_sqrt_L, 2) + np.power(e_dx, 2))
epsilon_total

0.05195960215433618

$$ \epsilon_{total} = 5.2 \% $$

In [23]:
132 * 0.052

6.864

$$ u = 132 \pm 7 $$

In [29]:
K = (0.001*m_bullets * np.power(u,2)) / 2
K

array([4.00984458, 4.82874255, 4.41806769, 4.28636285, 4.62078016])

In [30]:
K_mean = np.mean(K)
K_mean

4.4327595669

In [31]:
sigma_K = sigma(K)
sigma_K

0.2802353308004354

In [32]:
sigma_v2 = 2 * u * 7
sigma_v2

array([1748.74, 1922.76, 1839.18, 1825.88, 1880.9 ])

In [36]:
e_v2 = sigma_v2 / np.power(u,2)
e_v2 =np.mean(epsilon_v2)
e_v2

0.1064275323906136

In [38]:
e_tot = np.sqrt(np.power(e_m,2) + np.power(e_v2,2))
e_tot

0.10687677346254663

In [40]:
4.43 * 0.11

0.48729999999999996

$$ K = 4.43 \pm 0.49 $$